train:
  manifest_filepath: train.txt
  sample_rate: 16000
  batch_size: 1
  num_workers: 10
  pin_memory: true
  use_start_end_token: false
  trim_silence: false
  max_duration: 20.0
  min_duration: 0.1
  is_tarred: false
  tarred_audio_filepaths: null
  shuffle_n: 2048
  bucketing_strategy: "synced_randomized"
  bucketing_batch_size: null
  return_sample_id: false
  drop_last: false
  shuffle: false

test:
  manifest_filepath: test.txt
  sample_rate: 16000
  batch_size: 1
  num_workers: 10
  pin_memory: true
  use_start_end_token: false
  trim_silence: false
  max_duration: 20.0
  min_duration: 0.1
  is_tarred: false
  tarred_audio_filepaths: null
  shuffle_n: 2048
  bucketing_strategy: "synced_randomized"
  bucketing_batch_size: null
  return_sample_id: false
  drop_last: false
  shuffle: false

optim:
  name: adamw
  lr: 0.00001 # maximal learning rate
  betas: [0.9, 0.98]
  weight_decay: 0.001
